#!/usr/bin/env python

import sys
from datetime import datetime

from controller.controller import Flights as OldFlightsObj

"""README
- this script is to test the functionality without running with Flask
- used to test for controller
"""


class Flights(OldFlightsObj):
    """cli program to test controller"""

    def __init__(self):
        # initialize variables
        self.current_time = datetime.now()
        self.data = {}  # to store arrival/depart flights
        self.airlines = set()  # to store airline names

        # retrieve latest flights information
        self.updateArrival()
        print("[+] getting arrival data DONE")

        self.updateDeparture()
        print("[+] getting departure data DONE")

        # show name of airlines
        #print(self.getAirlines())


if __name__ == "__main__":
    if len(sys.argv) != 3:
        exit("./cli [arrival/depart] query")

    if sys.argv[1] == 'arrival':
        main = Flights()
        #flights = main.search('arrival', sys.argv[2])
        #flights = main.searchByTime("arrival", "Myanmar Airways International", "7pm")
    elif sys.argv[1] == 'depart':
        main = Flights()
        #flights = main.search('departure', sys.argv[2])
        #flights = main.searchByTime("departure", "Myanmar Airways International", "7pm")
    else:
        exit("./cli [arrival/depart] query")

    """
    if flights != []:
        print("Flight {} is scheduled at {}.".format(flights[0].getFlightNo(), flights[0].getScheduled()))
    else:
        print("Given flight not found")
    """